name: AI Words Mining (Simple)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  ai-words-mining:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > credentials.json
    
    - name: Run AI Words Mining
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
        GOOGLE_SHEETS_RANGE: ${{ secrets.GOOGLE_SHEETS_RANGE }}
        TARGET_URL: https://www.toolify.ai/new
      run: |
        python main.py
    
    - name: Clean up
      if: always()
      run: |
        rm -f credentials.json 